version: '3.9'

services:
  # Apache webserver service
  webserver:
    container_name: dev-PhpWebServer
    build:
    # Dockerfile path
      context: .
      dockerfile: Dockerfile
    # Mount the local ./app directory to /var/www/html in the container
    volumes:
      - ../:/var/www/html/
      - ./config/php.ini:/usr/local/etc/php/conf.d/php.ini
    # Map port 8000 on the host to port 80 on the container
    ports:
      - 80:80

  dbserver:
    image: mysql:5.7
    container_name: dev_mysql
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      #MYSQL_DATABASE: NAME_DB
      #MYSQL_USER: USER_DB
      #MYSQL_PASSWORD: PASS_DB
      MYSQL_TCP_PORT: 3306
    ports:
    - 3306:3306
    expose:
      - 3306

  phpmyadmin:
    depends_on:
      - dbserver
    image: phpmyadmin/phpmyadmin
    container_name: dev_mysql_phpmyadmin
    restart: always
    ports:
      - 8001:80
    environment:
      PMA_HOST: dbserver:3306
      MYSQL_ROOT_PASSWORD: root

volumes:
  mysql_data:
